//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RadverleihLib
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fortbewegungsmittel
    {
        public int Id { get; set; }
        public string Nummer { get; set; }
        public int Alter { get; set; }
        public System.DateTime Rückgabedatum { get; set; }
        public int ModellId { get; set; }
        public Nullable<int> AblageId { get; set; }
        public Nullable<int> KundeId { get; set; }
    
        public virtual Modell Modell { get; set; }
        public virtual Ablage Ablage { get; set; }
        public virtual Kunde Kunde { get; set; }
    }
}
