//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RadverleihLib
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class RadverleihModelContainer : DbContext
    {
        public RadverleihModelContainer()
            : base("name=RadverleihModelContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Kunde> Kundes { get; set; }
        public virtual DbSet<Fortbewegungsmittel> Fortbewegungsmittels { get; set; }
        public virtual DbSet<Modell> Modells { get; set; }
        public virtual DbSet<Ablage> Ablages { get; set; }
    }
}
